YOLOV3:
  CFG: "src/detector/YOLOv3/cfg/yolov3-tiny.cfg"
  WEIGHT: "src/detector/YOLOv3/weight/yolov3-tiny.weights"
  CLASS_NAMES: "src/detector/YOLOv3/cfg/coco.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4